// <auto-generated />
using System;
using AstroPhotographyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AstroPhotographyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200218182440_addedType")]
    partial class addedType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AstroPhotographyAPI.Models.DBPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAndTime");

                    b.Property<string>("Description");

                    b.Property<string>("Filters");

                    b.Property<string>("GuideCamera");

                    b.Property<string>("GuideScope");

                    b.Property<string>("MainCamera");

                    b.Property<string>("MainTelescope");

                    b.Property<string>("Mount");

                    b.Property<string>("Other");

                    b.Property<string>("PhotoLocation");

                    b.Property<string>("PhotoName");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("PhotoThumbnail");

                    b.Property<string>("PhotoType");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
